name: Deploy API Sports Zone

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */8 * * *'

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create Empty Commit
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit --allow-empty -m "Commit vacío"
          git push
